name: Pipeline CI/CD

on:
    push:
      branches:
      - main
      paths-ignore:
      - exercises/**

jobs:
    run-pipeline:
        runs-on: ubuntu-latest
        permissions:
          # necessary for commiting the updated report
          contents: write
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: main
        
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Install python deps
          uses: py-actions/py-dependency-install@v4
          with:
            path: "./main/requirements.txt"
        
        - name: Run Integration- and Unit-Tests
          run: |
            ./main/project/tests.sh
          
        - name: Creating report
          run: |
            jupyter nbconvert --execute --to html ./main/project/report_notebook.ipynb --output index --output-dir ./main
        
        - name: Commit updated report
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            file_pattern: 'index.html'
            repository: ./main
        # comment pipeline step, because it is executed during testing
        #- name: Run Data Pipeline
        #  run: |
        #    python ./main/data/data_pipeline.py