name: Pipeline CI/CD

on:
    push:
      branches:
      - main

jobs:
    run-pipeline:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: main
        
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11

        - name: Install python deps
          uses: py-actions/py-dependency-install@v4
          with:
            path: "./main/requirements.txt"
        
        - name: Run Integration- and Unit-Tests
          run: |
            ./main/project/tests.sh
        
        - name: Run Data Pipeline
          run: |
            python ./main/data/data_pipeline.py